language: node_js
node_js:
  - 12.16.1
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE bookreviewtest;" -U postgres
  - psql -c "CREATE USER rajdb WITH PASSWORD '123';" -U postgres
